name: Build Distributions

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pyautogui pygetwindow pynput

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile --windowed typewriter.py
          pyinstaller --onefile --windowed typewriter-receiver.py

      - name: Archive build artifacts
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: typewriter-${{ matrix.os }}
          path: |
            dist/typewriter
            dist/typewriter-receiver

      - name: Create GitHub Release
        if: success()
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        if: success()
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/typewriter
          asset_name: typewriter-${{ matrix.os }}
          asset_content_type: application/zip

      - name: Upload Release Asset
        if: success()
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/typewriter-receiver
          asset_name: typewriter-receiver-${{ matrix.os }}
          asset_content_type: application/zip
